name: project_gaia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  image_picker: ^1.2.1
  flutter_svg: 2.2.2
  percent_indicator: ^4.2.5
  flutter_arc_text: ^0.6.0
  google_fonts: ^6.3.2
  http: ^1.6.0
  firebase_core: ^4.3.0
  firebase_database: ^12.1.1
  firebase_storage: ^13.0.6
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_logo.png"
  web:
    generate: true
    image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
  - assets/images/

